# Generated by Django 6.0.4 on 2026-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health',
            field=models.CharField(choices=[('отличное', 'Отличное'), ('хорошее', 'Хорошее'), ('удовлетворительное', 'Удовлетворительное'), ('плохое', 'Плохое')], max_length=20, verbose_name='Здоровье'),
        ),
    ]
